- platform: template
  sensors:
#Sensor für RGB Farben
     rgb_color:
        friendly_name: rgb_color
        value_template: >-
          {% if state_attr('light.kugellampe','rgb_color') == (255,203,120) %} 255,228,183 #Fokus
          {% elif state_attr('light.kugellampe','rgb_color') == (255,227,183) %} 255,184,82 #Relax
          {% elif state_attr('light.kugellampe','rgb_color') == (255,184,82) %} 255,0,0 #Rot
          {% elif state_attr('light.kugellampe','rgb_color') == (255,0,0) %} 255,25,73 #Karmesinrot
          {% elif state_attr('light.kugellampe','rgb_color') == (255,29,76) %} 255,160,121 #Lachs
          {% elif state_attr('light.kugellampe','rgb_color') == (255,160,121) %} 255,166,0 #Orange
          {% elif state_attr('light.kugellampe','rgb_color') == (255,166,0) %} 255,210,0 #Gold
          {% elif state_attr('light.kugellampe','rgb_color') == (255,210,0) %} 254,255,0 #Gelb
          {% elif state_attr('light.kugellampe','rgb_color') == (252,255,0) %} 0,255,0 #Grün
          {% elif state_attr('light.kugellampe','rgb_color') == (0,255,0) %} 70,255,236 #Türkis
          {% elif state_attr('light.kugellampe','rgb_color') == (70,255,236) %} 146,224,255 #Himmelblau
          {% elif state_attr('light.kugellampe','rgb_color') == (146,224,255) %} 10,0,255 #Blau
          {% elif state_attr('light.kugellampe','rgb_color') == (19,8,255) %} 172,42,255 #Purpur
          {% elif state_attr('light.kugellampe','rgb_color') == (173,45,255) %} 253,11,255 #Magentarot
          {% elif state_attr('light.kugellampe','rgb_color') == (251,19,255) %} 255,190,203 Rose
          {% elif state_attr('light.kugellampe','rgb_color') == (255,190,203) %} 160,128,255 #Lavendel
          {% else %} 255,205,119 #Alltag
          {% endif %}
     rgb_color_invert:
        friendly_name: rgb_color_invert
        value_template: >-
          {% if state_attr('light.kugellampe','rgb_color') == (255,203,120) %} 160,128,255 #Lavendel
          {% elif state_attr('light.kugellampe','rgb_color') == (160,128,255) %} 255,190,203 #Rose
          {% elif state_attr('light.kugellampe','rgb_color') == (255,190,203) %} 253,11,255 # Magentarot
          {% elif state_attr('light.kugellampe','rgb_color') == (251,19,255) %} 172,42,255 #Purpur
          {% elif state_attr('light.kugellampe','rgb_color') == (173,45,255) %} 10,0,255 #Blau
          {% elif state_attr('light.kugellampe','rgb_color') == (19,8,255) %} 146,224,255 #Himmelblau
          {% elif state_attr('light.kugellampe','rgb_color') == (146,224,255) %} 70,255,236 #Türkis
          {% elif state_attr('light.kugellampe','rgb_color') == (70,255,236) %} 0,255,0 #Grün
          {% elif state_attr('light.kugellampe','rgb_color') == (0,255,0) %} 254,255,0 #Gelb
          {% elif state_attr('light.kugellampe','rgb_color') == (252,255,0) %} 255,210,0 #Gold
          {% elif state_attr('light.kugellampe','rgb_color') == (255,210,0) %} 255,166,0 #Orange
          {% elif state_attr('light.kugellampe','rgb_color') == (255,166,0) %} 255,160,121 #Lachs
          {% elif state_attr('light.kugellampe','rgb_color') == (255,160,121) %} 255,25,73 #Karmesinrot
          {% elif state_attr('light.kugellampe','rgb_color') == (255,29,76) %} 255,0,0 #Rot
          {% elif state_attr('light.kugellampe','rgb_color') == (255,0,0) %} 255,184,82 #Relax
          {% elif state_attr('light.kugellampe','rgb_color') == (255,184,82) %} 255,228,183 #Fokus
          {% else %} 255,205,119 #Alltag
          {% endif %}